### PR TITLE
Added login page link under Material Design

### PR DESCRIPTION
**Pull request by Kvaibhav01**
Link to resource: codeburst.io/make-a-material-design-login-page-with-flutter-the-basics-99d3acd80b18

### CODE REVIEW

**Comment by PoojaB26** [comment]
Your commit title was still not according to guidelines, so please take care of that next time. :)

**Comment by Kvaibhav01** [comment]
How it should be? Your commit format is: "Added <max 5 words summary of link> under "
So I think I've 3 words after _Added_ which summarises the link along with _Material Design_ which is the actual category name. 
Plus, I also added the link to the resources in the description. 

According to the example you gave "Added ML Kit Face Detection under Firebase", it would've been "Added Material Design login page under Material Design" which would be inconsistent I think.

Still, thank you for accepting the PR. I really want to contribute to the repo. 😃

**Comment by PoojaB26** [comment]
Hey, I'm talking about the commit description which is "Update README" in your case. Obviously your PR should be descriptive too and would be better if it follows the same guidelines, but later on when I look through the commits, its the commit descriptions that I would be seeing, and "Update README" is not descriptive enough. Was I able to show you the difference? :)

**Comment by Kvaibhav01** [comment]
Yes, got it! 😀

**Comment by Kvaibhav01** [comment]
Yes, got it! 😀

**Pull request merged**
